# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nightly Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    - run: cd packages/chrome-extension/dist && zip -r bbdash-nightly.zip . && mv bbdash-nightly.zip ../../..
    - run: cd ../../..
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BBDashNightly.zip
        path: bbdash-nightly.zip