# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Nightly Build

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    - run: cd packages/chrome-extension/dist && touch bbdash-nightly.tar.gz && tar --exclude=bbdash-nightly.tar.gz -cvzf bbdash-nightly.tar.gz . && mv bbdash-nightly.tar.gz ../../..
    - run: cd ../../..
    - name: Deploy Nightly
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: true
        title: "Nightly Build ${{ github.sha }}"
        files: |
          bbdash-nightly.tar.gz
